---
name: CI
on:
  push:
  pull_request_target:

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/master' && !startsWith(github.ref, 'refs/tags') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Lint code base
        uses: github/super-linter@v4.8.5
        env:
          FILTER_REGEX_EXCLUDE: (gradlew|gradle/.*|.github/workflows/cleanup.yaml)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup JDK
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'

      - name: Build
        run: ./gradlew build --info --no-daemon

  dependabot:
    name: Merge dependabot PR
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request_target' }}
    steps:
      - name: Fetch PR metadata
        uses: dependabot/fetch-metadata@v1.1.1
        id: dependabot-metadata
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Approve PR
        run: gh pr review --approve "$PR_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}

      - name: Merge PR
        run: gh pr merge --auto --squash "$PR_URL"
        if: ${{ steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
