---
name: CI
on:
  push:


jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/master' && !startsWith(github.ref, 'refs/tags') }}
    steps:
      - uses: actions/checkout@v2
      - uses: github/super-linter@v4
        env:
          FILTER_REGEX_EXCLUDE: (gradlew|gradle/.*)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'
      - run: ./gradlew build --no-daemon

  dependabot:
    name: Merge dependabot PR
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: dependabot/fetch-metadata@v1.1.1
        id: dependabot-metadata
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - run: gh pr review --approve "$PR_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}

      - run: gh pr merge --auto --squash "$PR_URL"
        if: ${{ steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
